# PluginVersions configuration
#
# To regenerate the default file content, delete the file and run:
#		/pv reload
#
# By default, we send anonymous plugin usage data to bstats.org.
# If you do not want to allow us to collect and send these data, change the value below to
#		metrics: false

metrics: true

# Check for updates.

check-for-updates: true
