# PluginVersions configuration
#
# To regenerate the default file content, delete the file and run:
#		/pv reload
#
# By default, we send anonymous plugin usage data to MCStats.org.
# If you want to allow us to collect and send these data, set the value below to
#		metrics: true
# and ensure that the related parameter in PluginMetrics/config.yml is set to
#		opt-out: false
# If you do not want to allow us to collect and send these data, change the value below to
#		metrics: false
# If you do not want any plugin to collect and send such data to MCStats.org,
# set the related parameter in PluginMetrics/config.yml to
#		opt-out: true
# which supercedes the settings for individual plugins.

metrics: true
