# PluginVersions configuration
#
# To regenerate the default file content, delete the file and run:
#		/pv reload
#

# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
#
enable-metrics: true

# Check for updates.
#
check-for-updates: true

# When executed at the console,
# {spacing} will enable tabular output (in-game does not support tabular output).
# To disable tabular output at the console, remove "{spacing"} from the format strings.
#
page-header-format: "PluginVersions ===== page {page} ====="
enabled-version-format: " - &a{name}{spacing}&e{version}"
disabled-version-format: " - &c{name}{spacing}&e{version}"
